device_widgets:
    vp-151mx:
      type: camera
      driver: view.widgets.device_widgets.camera_widget
      module: CameraWidget
      init:
        advanced_user: True
    488 nm:
      type: laser
      driver: view.widgets.device_widgets.laser_widget
      module: LaserWidget
      init:
        color: blue
        advanced_user: False
    561 nm:
      type: laser
      driver: view.widgets.device_widgets.laser_widget
      module: LaserWidget
      init:
        color: green
        advanced_user: False
    639 nm:
      type: laser
      driver: view.widgets.device_widgets.laser_widget
      module: LaserWidget
      init:
        color: red
        advanced_user: False
    z stage axis:
      type:   scanning_stage
      driver: view.widgets.device_widgets.stage_widget
      module: StageWidget
      init:
        advanced_user: False
    x stage axis:
      type: tiling_stage
      driver: view.widgets.device_widgets.stage_widget
      module: StageWidget
      init:
        advanced_user: False
    y stage axis:
      type:   tiling_stage
      driver: view.widgets.device_widgets.stage_widget
      module: StageWidget
      init:
        advanced_user: False
    pcie-6738:
      type: daq
      driver: view.widgets.device_widgets.ni_widget
      module: NIWidget
      init:
          advanced_user: True
          exposed_branches:
            tasks.ao_task.ports.tunable lens:
              parameters.amplitude_volts.channels:
                    CH488: 1.0
                    CH561: 1.0
                    CH639: 1.0
              parameters.offset_volts.channels:
                    CH488: 1.0
                    CH561: 1.0
                    CH639: 1.0
operation_widgets:
  volume_widget:
    init:
      fov_dimensions: [10.672384, 8.00128]
      coordinate_plane: ['x', 'y', 'z']
      unit: 'mm'
      channels:
        CH488:
          lasers: [488 nm]
          cameras: [vp-151mx]
        CH561:
          lasers: [561nm]
          cameras: [vp-151mx]
        CH639:
          lasers: [639nm]
          cameras: [vp-151mx]
      settings:
        cameras: [binning]
        lasers: [power_setpoint_mw]
        filter_wheels: [filter]