instrument_view:
  device_widgets:
      joystick:
        type: joystick
        driver: view.widgets.device_widgets.joystick_widget
        module: JoystickWidget
        init:
          advanced_user: False
      vp-151mx:
        type: camera
        driver: view.widgets.device_widgets.camera_widget
        module: CameraWidget
        init:
          advanced_user: True
      488 nm:
        type: laser
        driver: view.widgets.device_widgets.laser_widget
        module: LaserWidget
        init:
          color: blue
          advanced_user: False
      561 nm:
        type: laser
        driver: view.widgets.device_widgets.laser_widget
        module: LaserWidget
        init:
          color: green
          advanced_user: False
      639 nm:
        type: laser
        driver: view.widgets.device_widgets.laser_widget
        module: LaserWidget
        init:
          color: red
          advanced_user: False
      z stage axis:
        type:   scanning_stage
        driver: view.widgets.device_widgets.stage_widget
        module: StageWidget
        init:
          advanced_user: False
        updating_properties:
          - position_mm
      x stage axis:
        type: tiling_stage
        driver: view.widgets.device_widgets.stage_widget
        module: StageWidget
        init:
          advanced_user: False
        updating_properties:
          - position_mm
      y stage axis:
        type:   tiling_stage
        driver: view.widgets.device_widgets.stage_widget
        module: StageWidget
        init:
          advanced_user: False
        updating_properties:
          - position_mm
      n stage axis:
        type: focusing_stage
        driver: view.widgets.device_widgets.stage_widget
        module: StageWidget
        init:
          advanced_user: False
        updating_properties:
          - position_mm
      pcie-6738:
        type: daq
        driver: view.widgets.device_widgets.ni_widget
        module: NIWidget
        init:
            advanced_user: True
            exposed_branches:
              tasks.ao_task.ports.tunable lens:
                parameters.amplitude_volts.channels:
                      CH488: 0.078
                      CH561: 0.078
                      CH639: 0.078
                parameters.offset_volts.channels:
                      CH488: 2.448
                      CH561: 2.448
                      CH639: 2.448
              tasks.ao_task.ports.488 nm.parameters.max_volts.channels:
                CH488: 10.0
              tasks.ao_task.ports.561 nm.parameters.max_volts.channels:
                CH561: 10.0
              tasks.ao_task.ports.639 nm.parameters.max_volts.channels:
                CH639: 10.0
acquisition_view:
  fov_dimensions: [ 10.615616, 7.95872 ]
  coordinate_plane: [ '-x', 'y', 'z' ]
  unit: 'mm'
  channel_plan:
    init:
      properties:
        cameras: [ binning ]
        lasers: [ power_setpoint_mw ]
        focusing_stages: [ position_mm ]
  operation_widgets:
    vp-151mx:
      imaris:
        type: writer
        updating_properties:
          - progress
      robocopy:
        type: transfer
        updating_properties:
          - progress